Document: lunarg-tools
Title: Debian lunarg-tools Manual
Author: <insert document author here>
Abstract: This manual describes what lunarg-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lunarg-tools/lunarg-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/lunarg-tools/lunarg-tools.ps.gz

Format: text
Files: /usr/share/doc/lunarg-tools/lunarg-tools.text.gz

Format: HTML
Index: /usr/share/doc/lunarg-tools/html/index.html
Files: /usr/share/doc/lunarg-tools/html/*.html
